version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

commands:
  install-uv:
    description: |
      Install uv
    steps:
      - run:
          name: Install UV
          command: |
            curl -LsSf https://astral.sh/uv/install.sh | sh
            echo "export PATH=~/.cargo/bin:\${PATH}" >> $BASH_ENV
  
  save-test-results:
    description: |
      Save test results
    steps:
      - store_artifacts:
          path: test-reports/
      - store_test_results:
          path: test-reports     

executors:
  base:
    docker:
      - image: cimg/base:current
    resource_class: small

jobs:
  unit-tests:
    executor: base
    steps:
      - checkout
      - install-uv
      - run:
          name: Run tests
          command: |
            uv run tox -p
            uv run coverage xml -o .coverage-reports/coverage.xml
      - save-test-results
      - store_artifacts:
          path: .mypy-reports/
      - sonarcloud/scan

workflows:
  commit:
    # run on every commit
    jobs:
      - unit-tests:
          context:
            - SONARCLOUD
