version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

commands:
  install-uv:
    description: |
      Install uv
    steps:
      - run:
          name: Install UV
          command: |
            curl -LsSf https://astral.sh/uv/install.sh | sh
            echo "export PATH=~/.cargo/bin:\${PATH}" >> $BASH_ENV
  
  save-test-results:
    description: |
      Save test results
    steps:
      - store_artifacts:
          path: test-reports/
      - store_test_results:
          path: test-reports     

executors:
  base:
    docker:
      - image: cimg/base:current
    resource_class: small

jobs:
  coverage:
    executor: base
    steps:
      - checkout
      - install-uv
      - run:
          name: Run tests
          command: |
            uv run tox -e py311 -- --cov=pymetagen
            uv run coverage report -m
            uv run coverage xml -o .coverage-reports/coverage.xml
      - save-test-results
      - run:
          name: mypy
          command: |
            mkdir -p .mypy-reports
            uv run mypy | tee .mypy-reports/report.txt || true
            echo "Mypy report saved to .mypy-reports/report.txt"
      - sonarcloud/scan
  unit-test:
    executor: base
    steps:
      - checkout
      - install-uv
      - run:
          name: Run tests
          command: |
            uv run tox -e py39,py310,py312
      - save-test-results

workflows:
  commit:
    # run on every commit
    jobs:
      - unit-test
      - coverage:
          context:
            - SONARCLOUD
